sudo: false
language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4
install:
  - npm prune
  - npm update
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: dominic@dbarnes.info
  api_key:
    secure: ATp4BfTMNpESBiby/ck2h/Yj8S2uQBUDqh9fBmTi5/1/CRD1nTH3LrHufqfhggYPb0ehyj4+Kb78LgWG/3/6QczmMdpVhkep68oMbjwqPTLP++TVceP4iGPBVkUoqG09ggzXzugJYIbvSQmvN433TKxgioMPCTXBSFvfV2c6eudMTWFHBpgYPZsFB1474vLaz47jX17jK373WQyjrFqwQNsJV3ma7C4kBgqJ6tbmYrpXKttCedmt3DvxrTQv/Dr0KLL25nNX7xtwKO7tx8eYVPZN70d3NO+KDYNxnRO4kkO0bJX9KFmAfCJxkeELeGgiCY0EKzo0q+CYQHbRB1ZqwjvoXIYjMS0TXOWKDt+r5/GY89YLSx7VnxPg5yhHTGezDlJwGDunTn1At97g64XKFIobMf4poHRrY6V+Sj+wP8J4j20YOdXvLURkHQbom7GqHYoPVAYqkOzamSo6iXCh0XuQvBWp7nWSCeQ/g1+DB7NvR9HK/l3TjY4NUKpKWk2P89oOgcaIvVc1k8bkoxnb9XWtDCW7KU727Q9B8C4saOM7yytUTNUV15ECAlQjcMKPOOYAhgg9GIjkkd/OsxOcueDcKelrq6Y4Dql1OAxeFzs85v/WjR1Mk8ljC26OtWrB2TabvGvp2zzyslXTY8lsDZsjfMgjjQli1HtH1pFGWRM=
  on:
    tags: true
    repo: makojs/tree
